name: homebrew-store-cdn

services:
  homebrew-store-cdn:
    build: .
    image: fabiocdo/homebrew-store-cdn:latest
    container_name: homebrew-store-cdn
    ports:
      - "80:80"
    env_file:
      - ./settings.env
    volumes:
      - ./data:/data
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
