name: homebrew-store-cdn

services:
  homebrew-store-cdn:
    build: .
    image: fabiocdo/homebrew-store-cdn:latest
    container_name: homebrew-store-cdn
    ports:
      - "8080:80"
    environment:
      - BASE_URL=http://127.0.0.1:8080
      - LOG_LEVEL=info
      - PROCESS_WORKERS=4
      - PKG_WATCHER_ENABLED=true
      - AUTO_INDEXER_ENABLED=true
      - AUTO_FORMATTER_ENABLED=true
      - AUTO_FORMATTER_MODE=none
      - AUTO_FORMATTER_TEMPLATE={title} [{titleid}][{apptype}]
      - AUTO_SORTER_ENABLED=true
      - PERIODIC_SCAN_SECONDS=30
    volumes:
      - ./data:/data
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
