name: homebrew-store-cdn

services:
  homebrew-store-cdn:
    build: .
    image: fabiocdo/homebrew-store-cdn:latest
    container_name: homebrew-store-cdn
    ports:
      - "8080:80"
    volumes:
      - ${CDN_DATA_DIR:-./data}:/data
    environment:
      - BASE_URL=http://127.0.0.1:8080
      - GENERATE_JSON_PERIOD=2
    restart: unless-stopped
