name: homebrew-store-cdn

services:
  homebrew-store-cdn:
    build: .
    image: fabiocdo/homebrew-store-cdn:latest
    container_name: homebrew-store-cdn
    ports:
      - "8080:80"
    environment:
      - BASE_URL=http://127.0.0.1:8080
      - PKG_WATCHER_ENABLED=true
      - AUTO_INDEXER_ENABLED=true
      - LOG_LEVEL=debug
      - AUTO_RENAMER_ENABLED=false
      - AUTO_RENAMER_TEMPLATE={title} [{titleid}][{apptype}]
      - AUTO_RENAMER_MODE=none
      - AUTO_MOVER_ENABLED=true
      - AUTO_MOVER_EXCLUDED_DIRS=app
    volumes:
      - ./data:/data
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
