name: homebrew-store-cdn

services:
  homebrew-store-cdn:
    build: .
    image: fabiocdo/homebrew-store-cdn:latest
    container_name: homebrew-store-cdn
    ports:
      - "8080:80"
    environment:
      - BASE_URL=http://127.0.0.1:8080
      - AUTO_GENERATE_JSON_PERIOD=2
      - AUTO_RENAME_PKGS=false
      - AUTO_RENAME_TEMPLATE={title} [{titleid}][{apptype}]
      - AUTO_RENAME_TITLE_MODE=none
    volumes:
      - ./data:/data
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
